run:
	cd /home/broten15/Git-repos/personal/chinese-grammar-vocab/parser ; /usr/bin/env /usr/lib/jvm/java-11-openjdk-amd64/bin/java -cp /home/broten15/.vscode-server/data/User/workspaceStorage/ae2f286b6a3f961fca31c85bb01f0127/redhat.java/jdt_ws/parser_83d06aa3/bin Parser > out.txt
	